apiVersion: v2
name: nginx-ingress
description: NGINX Ingress Controller for homelab
version: 1.0.0
dependencies:
- name: ingress-nginx
  version: 4.13.0
  repository: https://kubernetes.github.io/ingress-nginx
