# NGINX Ingress Controller configuration for Pi 5 homelab
controller:
  # Resource optimization for Pi 5
  replicaCount: 1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  # LoadBalancer configuration via MetalLB
  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.79.30"
    annotations:
      metallb.universe.tf/allow-shared-ip: "nginx-ingress"

  # Node selector for ARM64
  nodeSelector:
    kubernetes.io/arch: arm64

  # Ingress class configuration
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"

  # Metrics configuration for Prometheus
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      additionalLabels:
        app.kubernetes.io/part-of: nginx-ingress

  # Configuration for homelab
  config:
    # Basic security settings
    ssl-redirect: "false"
    force-ssl-redirect: "false"

    # Performance tuning for Pi
    worker-processes: "2"
    max-worker-connections: "1024"

  # Security settings
  allowSnippetAnnotations: false

  # Admission webhook configuration
  admissionWebhooks:
    enabled: false
    patch:
      nodeSelector:
        kubernetes.io/arch: arm64

# Default backend (disabled for resource optimization)
defaultBackend:
  enabled: false

# RBAC configuration
rbac:
  create: true

# Service account
serviceAccount:
  create: true
  name: nginx-ingress-controller
