# ArgoCD Helm values optimized for Pi 5 homelab
global:
  image:
    tag: "v2.13.2"  # Latest stable v2.x - v3.x requires validation for ARM64 compatibility
  nodeSelector:
    kubernetes.io/arch: arm64

## Dex (OAuth2/OIDC provider) - disabled for homelab
dex:
  enabled: false

## Server configuration
server:
  # Resource limits for Pi 5
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  # LoadBalancer configuration via MetalLB
  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.79.32"
    annotations:
      metallb.universe.tf/allow-shared-ip: "argocd"

  # Ingress configuration - disabled in favor of LoadBalancer
  ingress:
    enabled: false

  # ArgoCD server configuration
  config:
    # Repositories configuration
    repositories: |
      - type: git
        url: https://github.com/Damianjsp/homelab-gitops
        name: homelab-gitops

    # Application configuration
    application.instanceLabelKey: argocd.argoproj.io/instance

    # Resource customizations for better Pi 5 compatibility
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil then
        if obj.status.health ~= nil then
          hs.status = obj.status.health.status
          if obj.status.health.message ~= nil then
            hs.message = obj.status.health.message
          end
        end
      end
      return hs

## Repository Server
repoServer:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 750m
      memory: 1Gi

## Application Controller
controller:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1500m
      memory: 2Gi

  # Metrics configuration for Prometheus
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: argocd

## ApplicationSet Controller
applicationSet:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

## Notifications Controller
notifications:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

## Redis for caching
redis:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
