# File: applications/core-services/monitoring.yml
# This follows your exact existing pattern

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: core-services  # Using your existing core-services project
  source:
    repoURL: https://github.com/Damianjsp/homelab-gitops
    targetRevision: main
    path: infrastructure/base/monitoring  # Following your pattern
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true  # Same as your ChromaDB app
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
