# Kustomization file for PostgreSQL
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgresql

resources:
  - postgresql-namespace.yml
  - postgresql-pv.yml
  - postgresql-pvc.yml
  - postgresql-sealed-secret.yml  # Using sealed secret instead of plaintext
  - postgresql-configmap.yml
  - postgresql-deployment.yml
  - postgresql-service.yml

labels:
  - includeSelectors: true
    pairs:
      app: postgresql
      managed-by: argocd
