# PostgreSQL Sealed Secret
# This is a sealed secret encrypted with the sealed-secrets controller
# To generate a new sealed secret, run:
#
# 1. First, create a plaintext secret (don't commit this):
#    kubectl create secret generic postgresql-credentials \
#      --from-literal=POSTGRES_USER=postgres \
#      --from-literal=POSTGRES_PASSWORD=YOUR_PASSWORD_HERE \
#      --from-literal=POSTGRES_DB=homelab \
#      --namespace=postgresql \
#      --dry-run=client -o yaml | kubeseal -f - -w postgresql-sealed-secret.yml
#
# 2. Then commit only the sealed-secret.yml file to git
# 3. The sealed-secrets controller will automatically decrypt it in the cluster
#
# To change the password, repeat the above steps with the new password

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: postgresql
  labels:
    app: postgresql
spec:
  encryptedData:
    # IMPORTANT: Replace these with your actual sealed values!
    # These are placeholders and won't work - generate your own with kubeseal
    POSTGRES_DB: AgBvG7z... # REPLACE WITH YOUR SEALED VALUE
    POSTGRES_PASSWORD: AgCdH8m... # REPLACE WITH YOUR SEALED VALUE
    POSTGRES_USER: AgDeF9n... # REPLACE WITH YOUR SEALED VALUE
  template:
    metadata:
      name: postgresql-credentials
      namespace: postgresql
      labels:
        app: postgresql
    type: Opaque
