# PostgreSQL Secrets
# WARNING: In production, use sealed-secrets or external-secrets for better security
# For now, using base64 encoded strings (easily decodable - not secure for production)
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: postgresql
  labels:
    app: postgresql
type: Opaque
stringData:
  # Change these values to your desired password
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "homelab-postgres-2024"  # Change this!
  POSTGRES_DB: homelab
