# PostgreSQL Internal Service - ClusterIP for internal cluster communication
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: postgresql
  labels:
    app: postgresql
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgresql

---
# PostgreSQL External Service - LoadBalancer for local network access
apiVersion: v1
kind: Service
metadata:
  name: postgresql-external
  namespace: postgresql
  labels:
    app: postgresql
  annotations:
    metallb.universe.tf/allow-shared-ip: "postgresql"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.79.30
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgresql
