apiVersion: v1
kind: Service
metadata:
  name: redis-n8n
  namespace: ai-services
  labels:
    app: redis-n8n
  annotations:
    description: "Redis Cache Service for N8N"
spec:
  type: ClusterIP
  selector:
    app: redis-n8n
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  sessionAffinity: None
