# chromadb-backup-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: chromadb-backup
  namespace: ai-services
spec:
  schedule: "0 4 * * *"  # Daily at 4:00 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: alpine:latest
            command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache tar gzip
              timestamp=$(date +%Y%m%d-%H%M%S)
              backup_file="chroma-k3s-backup-$timestamp.tar.gz"
              echo "[$(date)] Starting ChromaDB K3s backup..."
              tar -czf "/nfs-backup/$backup_file" -C /data .
              backup_size=$(du -h "/nfs-backup/$backup_file" | cut -f1)
              echo "[$(date)] Backup completed: $backup_file ($backup_size)"
              # Keep last 7 backups (1 week of daily backups)
              ls -t /nfs-backup/chroma-k3s-backup-*.tar.gz | tail -n +8 | xargs -r rm
              echo "[$(date)] Cleaned old backups, keeping last 7 days"
            volumeMounts:
            - name: chromadb-data
              mountPath: /data
              readOnly: true
            - name: nfs-backup
              mountPath: /nfs-backup
          volumes:
          - name: chromadb-data
            persistentVolumeClaim:
              claimName: chromadb-data-pvc
          - name: nfs-backup
            nfs:
              server: 192.168.79.2
              path: /mnt/nfs-share/backups
          restartPolicy: OnFailure
