# chromadb-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-data-pvc
  namespace: ai-services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
