apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: ai-services
  labels:
    app: n8n
data:
  # N8N Core Configuration
  N8N_HOST: "0.0.0.0"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "https"
  NODE_ENV: "production"

  # Database Configuration
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "postgresql.postgresql.svc.cluster.local"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_SSL: "false"

  # Redis Configuration for caching and queue
  QUEUE_BULL_REDIS_HOST: "redis-n8n"
  QUEUE_BULL_REDIS_PORT: "6379"
  QUEUE_BULL_REDIS_DB: "0"

  # Execution Configuration
  EXECUTIONS_DATA_PRUNE: "true"
  EXECUTIONS_DATA_PRUNE_MAX_AGE: "86400"  # 1 day in seconds
  EXECUTIONS_DATA_SAVE_ON_ERROR: "all"
  EXECUTIONS_DATA_SAVE_ON_SUCCESS: "all"

  # Security and Logs
  LOG_LEVEL: "info"
  N8N_LOG_OUTPUT: "console"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
  TZ: "Europe/Madrid"

  # Telemetry (disabled)
  N8N_DIAGNOSTICS_ENABLED: "false"

  # Webhook Configuration (will be set via service DNS)
  N8N_WEBHOOK_URL: "https://n8n.homelab/"

  # Generic OAuth2 (optional - for future integration)
  GENERIC_OAUTH_ENABLED: "false"
