apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secrets
  namespace: ai-services
  labels:
    app: n8n
spec:
  encryptedData:
    # TODO: Replace with sealed secret values
    # Generate sealed secret with:
    # echo -n "value" | kubectl create secret generic n8n-secrets --dry-run=client --from-file=DB_POSTGRESDB_USER=/dev/stdin -o yaml | kubeseal -f -
    DB_POSTGRESDB_USER: ""
    DB_POSTGRESDB_PASSWORD: ""
    N8N_ENCRYPTION_KEY: ""
    N8N_BASIC_AUTH_ACTIVE: ""
  template:
    metadata:
      name: n8n-secrets
      namespace: ai-services
      labels:
        app: n8n
    type: Opaque
