apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

resources:
  - sealed-secrets-controller.yml

labels:
  - includeSelectors: true
    pairs:
      app: sealed-secrets
      managed-by: argocd
