apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoriametrics-storage
  namespace: monitoring
  labels:
    app: victoriametrics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
