apiVersion: v1
kind: ServiceAccount
metadata:
  name: victoriametrics
  namespace: monitoring
  labels:
    app: victoriametrics

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: victoriametrics
  labels:
    app: victoriametrics
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods", "nodes", "nodes/proxy", "nodes/metrics"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics", "/metrics/*"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: victoriametrics
  labels:
    app: victoriametrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: victoriametrics
subjects:
- kind: ServiceAccount
  name: victoriametrics
  namespace: monitoring
