apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: monitoring
  labels:
    app: victoriametrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8428"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.79.36
  selector:
    app: victoriametrics
  ports:
  - port: 8428
    targetPort: 8428
    protocol: TCP
    name: http
