apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sure-namespace.yml
  - sure-pvc.yml
  - sure-redis.yml
  - sure-deployment.yml
  - sure-worker.yml
  - sure-service.yml
