apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sure-storage
  namespace: sure
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
