apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
  labels:
    app: grafana
data:
  grafana.ini: |
    [server]
    http_port = 3000
    domain = 192.168.79.37  # Use IP instead of domain
    root_url = http://192.168.79.37:3000

    [database]
    type = sqlite3
    path = /var/lib/grafana/grafana.db

    [analytics]
    reporting_enabled = false
    check_for_updates = false

    [security]
    admin_user = $__env{GF_SECURITY_ADMIN_USER}
    admin_password = $__env{GF_SECURITY_ADMIN_PASSWORD}

    [plugins]
    enable_alpha = false

    [log]
    level = warn
    mode = console

    [alerting]
    enabled = false  # Save resources

    [unified_alerting]
    enabled = false

    [auth.anonymous]
    enabled = false

  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: VictoriaMetrics
      type: prometheus
      url: http://victoriametrics.monitoring.svc.cluster.local:8428
      access: proxy
      isDefault: true
      editable: true
      jsonData:
        httpMethod: POST
        manageAlerts: false
        prometheusType: Prometheus
        prometheusVersion: 2.40.0
        cacheLevel: 'High'

  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'homelab'
      orgId: 1
      folder: 'Homelab'
      type: file
      disableDeletion: false
      editable: true
      updateIntervalSeconds: 60
      allowUiUpdates: true
      options:
        path: /etc/grafana/dashboards

  node-exporter-full.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Node Exporter Full",
        "tags": ["node-exporter", "homelab"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "CPU Usage",
            "type": "stat",
            "targets": [
              {
                "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\",instance=~\".*\"}[5m])) * 100)",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "percent",
                "color": {"mode": "palette-classic"}
              }
            },
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Memory Usage",
            "type": "stat",
            "targets": [
              {
                "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "percent",
                "color": {"mode": "palette-classic"}
              }
            },
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0}
          },
          {
            "id": 3,
            "title": "Disk Usage",
            "type": "timeseries",
            "targets": [
              {
                "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "percent",
                "color": {"mode": "palette-classic"}
              }
            },
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 8}
          },
          {
            "id": 4,
            "title": "Network Traffic",
            "type": "timeseries",
            "targets": [
              {
                "expr": "irate(node_network_receive_bytes_total{device!=\"lo\"}[5m])",
                "legendFormat": "{{device}} - Receive",
                "refId": "A"
              },
              {
                "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\"}[5m])",
                "legendFormat": "{{device}} - Transmit",
                "refId": "B"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "binBps",
                "color": {"mode": "palette-classic"}
              }
            },
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 16}
          }
        ],
        "time": {"from": "now-1h", "to": "now"},
        "timepicker": {},
        "templating": {
          "list": [
            {
              "name": "instance",
              "type": "query",
              "query": "label_values(node_cpu_seconds_total, instance)",
              "refresh": 1,
              "includeAll": true,
              "allValue": ".*"
            }
          ]
        },
        "refresh": "30s"
      }
    }
